name: form_it
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1

  device_preview: ^0.6.2-beta

  user_repository:
    path: user_repository

  people_repository:
    path: people_repository
  lite_rolling_switch: ^0.1.1
  flutter_slidable: ^0.5.7

  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  google_sign_in: ^4.0.1+1
  meta: ^1.1.6
  rxdart: ^0.25.0
  font_awesome_flutter: ^8.8.1

  flutter_bloc: ^6.1.1
  equatable: ^1.2.5

  provider: ^4.3.2+3
  flutter_spinkit: "^4.1.2"
  cupertino_icons: ^1.0.1
  flutter_svg: ^0.19.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
#  integration_test:
#    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
#  intl: ^0.17.0-nullsafety.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/langs/

  fonts:
    - family:  Navicons
      fonts:
        - asset: fonts/Navicons.ttf

