name: user_repository

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.18.2
  google_sign_in: ^4.0.1+1
  firebase_analytics: ^6.3.0