name: user_repository

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.1
  firebase_analytics: ^7.1.1
  cloud_firestore: ^1.0.1